import type { BackupFile, EvidenceFile, MaintenanceRecord, Settings } from './types'
import { escapeCsv, hashFile } from './utils'

const HASH_PATTERN = /^[a-f0-9]{64}$/i
const DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/
// IDs are generated by crypto.randomUUID(). Restrict restores to that same
// canonical format so imported IDs are safe to use as storage and DOM keys.
const ID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const THEMES = new Set<Settings['theme']>(['light', 'dark', 'system'])

function restoreError(message: string): Error {
  return new Error(`${message} No data was changed.`)
}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function isString(value: unknown, maxLength: number, required = false): value is string {
  return typeof value === 'string' && value.length <= maxLength && (!required || value.trim().length > 0)
}

function isId(value: unknown): value is string {
  return typeof value === 'string' && ID_PATTERN.test(value)
}

function isDate(value: unknown, optional = false): value is string {
  if (optional && value === '') return true
  if (typeof value !== 'string' || !DATE_PATTERN.test(value)) return false
  const date = new Date(`${value}T12:00:00Z`)
  return !Number.isNaN(date.valueOf()) && date.toISOString().slice(0, 10) === value
}

function isTimestamp(value: unknown): value is string {
  return typeof value === 'string' && value.length <= 40 && Number.isFinite(Date.parse(value))
}

function readSettings(value: unknown): Settings {
  if (!isObject(value)
    || !isString(value.homeName, 80, true)
    || !isString(value.address, 160)
    || typeof value.theme !== 'string'
    || !THEMES.has(value.theme as Settings['theme'])) {
    throw restoreError('The backup has invalid home settings.')
  }
  return { homeName: value.homeName.trim(), address: value.address.trim(), theme: value.theme as Settings['theme'] }
}

function readRecord(value: unknown, index: number): MaintenanceRecord {
  const label = `Record ${index + 1}`
  if (!isObject(value)) throw restoreError(`${label} is not a complete maintenance record.`)
  if (!isId(value.id)) throw restoreError(`${label} has an invalid identifier.`)
  if (!isString(value.system, 80, true)) throw restoreError(`${label} has an invalid appliance or system.`)
  if (!isString(value.task, 120, true)) throw restoreError(`${label} has an invalid completed task.`)
  if (!isDate(value.completedDate)) throw restoreError(`${label} has an invalid completion date.`)
  if (!isString(value.provider, 100)) throw restoreError(`${label} has an invalid provider.`)
  if (value.cost !== null && (typeof value.cost !== 'number' || !Number.isFinite(value.cost) || value.cost < 0 || value.cost > 9_999_999)) {
    throw restoreError(`${label} has an invalid cost.`)
  }
  if (!isDate(value.nextDueDate, true)) throw restoreError(`${label} has an invalid next-due date.`)
  if (!isString(value.notes, 800)) throw restoreError(`${label} has invalid notes.`)
  if (!isTimestamp(value.createdAt) || !isTimestamp(value.updatedAt)) throw restoreError(`${label} has invalid history dates.`)

  const hasAttachment = value.attachmentId !== null
  if (hasAttachment) {
    if (!isId(value.attachmentId)
      || !isString(value.attachmentName, 255, true)
      || !isString(value.attachmentType, 200, true)
      || typeof value.attachmentHash !== 'string'
      || !HASH_PATTERN.test(value.attachmentHash)) {
      throw restoreError(`${label} has incomplete evidence metadata.`)
    }
  } else if (value.attachmentName !== null || value.attachmentType !== null || value.attachmentHash !== null) {
    throw restoreError(`${label} has evidence metadata without an evidence file.`)
  }

  return {
    id: value.id,
    system: value.system.trim(),
    task: value.task.trim(),
    completedDate: value.completedDate,
    provider: value.provider.trim(),
    cost: value.cost as number | null,
    nextDueDate: value.nextDueDate,
    notes: value.notes.trim(),
    attachmentId: value.attachmentId as string | null,
    attachmentName: value.attachmentName as string | null,
    attachmentType: value.attachmentType as string | null,
    attachmentHash: typeof value.attachmentHash === 'string' ? value.attachmentHash.toLowerCase() : null,
    createdAt: value.createdAt,
    updatedAt: value.updatedAt,
  }
}

function download(blob: Blob, name: string): void {
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = name
  link.click()
  URL.revokeObjectURL(url)
}

function blobToDataUrl(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = () => resolve(String(reader.result))
    reader.onerror = () => reject(reader.error)
    reader.readAsDataURL(blob)
  })
}

function dataUrlToBlob(dataUrl: string): Blob {
  const match = /^data:([^;,]+);base64,([A-Za-z0-9+/]*={0,2})$/.exec(dataUrl)
  if (!match) throw restoreError('An evidence file has invalid encoded data.')
  const [, type, encoded] = match
  let binary: string
  try {
    binary = atob(encoded)
  } catch {
    throw restoreError('An evidence file has invalid encoded data.')
  }
  const bytes = new Uint8Array(binary.length)
  for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index)
  return new Blob([bytes], { type })
}

export async function downloadBackup(records: MaintenanceRecord[], attachments: EvidenceFile[], settings: Settings): Promise<void> {
  const data: BackupFile = {
    format: 'home-maintenance-receipts',
    version: 1,
    exportedAt: new Date().toISOString(),
    settings,
    records,
    attachments: await Promise.all(attachments.map(async ({ blob, ...file }) => ({ ...file, dataUrl: await blobToDataUrl(blob) }))),
  }
  download(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }), `home-maintenance-backup-${new Date().toISOString().slice(0, 10)}.json`)
}

export function downloadCsv(records: MaintenanceRecord[]): void {
  const headers = ['System', 'Completed task', 'Completed date', 'Provider', 'Cost', 'Next due', 'Notes', 'Attachment name', 'SHA-256']
  const rows = records.map((record) => [record.system, record.task, record.completedDate, record.provider, record.cost, record.nextDueDate, record.notes, record.attachmentName ?? '', record.attachmentHash ?? ''])
  const csv = [headers, ...rows].map((row) => row.map(escapeCsv).join(',')).join('\r\n')
  download(new Blob([csv], { type: 'text/csv;charset=utf-8' }), `home-maintenance-log-${new Date().toISOString().slice(0, 10)}.csv`)
}

export async function parseBackup(file: File): Promise<{ records: MaintenanceRecord[]; attachments: EvidenceFile[]; settings: Settings }> {
  let data: unknown
  try {
    data = JSON.parse(await file.text()) as unknown
  } catch {
    throw restoreError('That file is not valid JSON.')
  }
  if (!isObject(data)
    || data.format !== 'home-maintenance-receipts'
    || data.version !== 1
    || !isTimestamp(data.exportedAt)
    || !Array.isArray(data.records)
    || !Array.isArray(data.attachments)) {
    throw new Error('Choose a version 1 Home Maintenance Receipts backup.')
  }

  const settings = readSettings(data.settings)
  const records = data.records.map(readRecord)
  const recordIds = new Set<string>()
  records.forEach((record, index) => {
    if (recordIds.has(record.id)) throw restoreError(`Record ${index + 1} repeats an existing identifier.`)
    recordIds.add(record.id)
  })

  const attachments: EvidenceFile[] = []
  const attachmentIds = new Set<string>()
  for (let index = 0; index < data.attachments.length; index += 1) {
    const value = data.attachments[index]
    const label = `Evidence file ${index + 1}`
    if (!isObject(value)
      || !isId(value.id)
      || !isString(value.name, 255, true)
      || !isString(value.type, 200, true)
      || typeof value.size !== 'number'
      || !Number.isSafeInteger(value.size)
      || value.size < 0
      || value.size > 15_000_000
      || typeof value.hash !== 'string'
      || !HASH_PATTERN.test(value.hash)
      || typeof value.dataUrl !== 'string') {
      throw restoreError(`${label} has invalid metadata.`)
    }
    if (attachmentIds.has(value.id)) throw restoreError(`${label} repeats an existing identifier.`)
    const blob = dataUrlToBlob(value.dataUrl)
    if (blob.size !== value.size || blob.type !== value.type) throw restoreError(`${label} does not match its size or file type.`)
    const actualHash = await hashFile(blob)
    if (actualHash !== value.hash.toLowerCase()) throw restoreError(`${label} does not match its SHA-256 evidence hash.`)
    attachments.push({ id: value.id, name: value.name, type: value.type, size: value.size, hash: actualHash, blob })
    attachmentIds.add(value.id)
  }

  const attachmentsById = new Map(attachments.map((attachment) => [attachment.id, attachment]))
  records.forEach((record, index) => {
    if (!record.attachmentId) return
    const attachment = attachmentsById.get(record.attachmentId)
    if (!attachment) throw restoreError(`Record ${index + 1} refers to a missing evidence file.`)
    if (record.attachmentName !== attachment.name || record.attachmentType !== attachment.type || record.attachmentHash !== attachment.hash) {
      throw restoreError(`Record ${index + 1} does not match its evidence metadata.`)
    }
  })
  const referencedIds = new Set(records.flatMap((record) => record.attachmentId ? [record.attachmentId] : []))
  attachments.forEach((attachment, index) => {
    if (!referencedIds.has(attachment.id)) throw restoreError(`Evidence file ${index + 1} is not linked to a maintenance record.`)
  })

  return { records, attachments, settings }
}
